[[redirects]]
from = "/index.html"
to = "/"
status = 301

[[redirects]]
  from = "*"
  to = "https://www.germanmagicfarm.com/:splat"
  status = 301
  force = true

[[redirects]]
from = "/services.html"
to = "https://www.germanmagicfarm.com/services"
status = 301

[[redirects]]
from = "/clinics.html"
to = "/clinics"
status = 301

[[redirects]]
from = "/contact.html"
to = "/contact"
status = 301

[[redirects]]
from = "/sales.html"
to = "/"
status = 301

[[redirects]]
from = "/for-lease.html"
to = "/"
status = 301

[[redirects]]
from = "/meet-pam-bauer.html"
to = "/meet-pam-bauer"
status = 301

[[redirects]]
from = "/photo-gallery.html"
to = "/"
status = 301




